<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN-5CD5329NXX" failures="2" tests="2" name="Test1" time="8.899" errors="0" timestamp="2025-10-17T16:05:22 IST">
  <testcase classname="oct17.App" name="login" time="2.675">
    <failure type="java.lang.AssertionError" message="expected [bbb] but found [aaa]">
      <![CDATA[java.lang.AssertionError: expected [bbb] but found [aaa]
at oct17.App.login(App.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="oct17.App" name="login1" time="4.546">
    <failure type="java.lang.AssertionError" message="expected [bbb] but found [aa]">
      <![CDATA[java.lang.AssertionError: expected [bbb] but found [aa]
at oct17.App.login1(App.java:36)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- login1 -->
</testsuite> <!-- Test1 -->
